# Generated by Django 6.0.5 on 2026-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password_hs', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
